apiVersion: v1
stringData:
  password: pgbouncer_pass
  users.txt: '"pgbouncer" "md5a5d5d13b416ffb94d2034c4564ba8155"'
kind: Secret
metadata:
  labels:
    crunchy-pgbouncer: "true"
    pg-cluster: some-name
    vendor: crunchydata
  name: some-name-pgbouncer-secret
type: Opaque
---
apiVersion: v1
stringData:
  password: postgres_pass
  username: postgres
kind: Secret
metadata:
  labels:
    pg-cluster: some-name
    vendor: crunchydata
  name: some-name-postgres-secret
type: Opaque
---
apiVersion: v1
stringData:
  password: primaryuser_pass
  username: primaryuser
kind: Secret
metadata:
  labels:
    pg-cluster: some-name
    vendor: crunchydata
  name: some-name-primaryuser-secret
type: Opaque
---
apiVersion: v1
stringData:
  password: some-name_pass
  username: some-name
kind: Secret
metadata:
  labels:
    pg-cluster: some-name
    vendor: crunchydata
  name: some-name-some-name-secret
type: Opaque
---
apiVersion: v1
data:
  password: YWRtaW4=
  username: YWRtaW4=
kind: Secret
metadata:
  name: some-name-pmm-secret
type: Opaque
