apiVersion: v1
kind: Secret
metadata:
  name: some-name-users-secrets
type: Opaque
stringData:
  pgbouncer: pgbouncer_pass
  postgres: postgres_pass
  primaryuser: primaryuser_pass
  some-name: some-name_pass
---
apiVersion: v1
data:
  password: YWRtaW4=
  username: YWRtaW4=
kind: Secret
metadata:
  name: some-name-pmm-secret
type: Opaque
