[req]
distinguished_name = subject
x509_extensions = extensions
prompt = no

[subject]
CN = postgres-operator-ca

[extensions]
basicConstraints = critical,CA:true,pathlen:0
keyUsage = critical,keyCertSign,cRLSign
subjectKeyIdentifier = hash
