[req]
distinguished_name = subject
req_extensions = extensions
prompt = no

[subject]
CN = <common-name>

[extensions]
basicConstraints = critical,CA:false
keyUsage = critical,digitalSignature
extendedKeyUsage = <purpose>
subjectAltName = @names

[names]
