apiVersion: pg.percona.com/v1
kind: PerconaPGCluster
metadata:
  labels:
    pgo-version: 9.9.9
  name: cluster1
spec:
  #  secretsName: cluster1-users
  #  sslCA: cluster1-ssl-ca
  #  sslSecretName: cluster1-ssl-keypair
  #  sslReplicationSecretName: cluster1-ssl-keypair
  #  upgradeOptions:
  #    versionServiceEndpoint: https://check.percona.com
  #    apply: disabled
  #    schedule: "0 4 * * *"
  database: pgdb
  port: "5432"
  user: pguser
  disableAutofail: false
  tlsOnly: false
  standby: false
  pause: false
  keepData: true
  keepBackups: true
  #  pgDataSource:
  #    restoreFrom: ""
  #    restoreOpts: ""
  #  tablespaceStorages:
  #    lake:
  #      volumeSpec:
  #        size: 1G
  #        accessmode: ReadWriteOnce
  #        storagetype: dynamic
  #        storageclass: ""
  #        matchLabels: ""
  #  walStorage:
  #    volumeSpec:
  #      size: 1G
  #      accessmode: ReadWriteOnce
  #      storagetype: dynamic
  #      storageclass: ""
  #      matchLabels: ""
  userLabels:
    pgo-version: 9.9.9
  pgPrimary:
    image: percona/percona-postgresql-operator:1.3.0-ppg14-postgres-ha
    #    imagePullPolicy: Always
    resources:
      requests:
        cpu: 500m
        memory: "256Mi"
        #      limits:
        #        cpu: 500m
        #        memory: "256Mi"
        #    affinity:
        #      antiAffinityType: preferred
    tolerations: []
    volumeSpec:
      size: 1G
      accessmode: ReadWriteOnce
      storagetype: dynamic
      storageclass: ""
      #      matchLabels: ""
    expose:
      serviceType: ClusterIP
      #      loadBalancerSourceRanges:
      #      annotations:
      #        pg-cluster-annot: cluster1
      #      labels:
      #        pg-cluster-label: cluster1
      #    customconfig: ""
  pmm:
    enabled: false
    image: percona/pmm-client:2.26.0
    #    imagePullPolicy: Always
    serverHost: monitoring-service
    serverUser: admin
    pmmSecret: cluster1-pmm-secret
    resources:
      requests:
        memory: 200M
        cpu: 500m
        #      limits:
        #        cpu: "1"
        #        memory: "400M"
  backup:
    image: percona/percona-postgresql-operator:1.3.0-ppg14-pgbackrest
    #    imagePullPolicy: Always
    backrestRepoImage: percona/percona-postgresql-operator:1.3.0-ppg14-pgbackrest-repo
    resources:
      requests:
        cpu: "200m"
        memory: "48Mi"
        #      limits:
        #        cpu: "1"
        #        memory: "64Mi"
        #    affinity:
        #      antiAffinityType: preferred
    volumeSpec:
      size: 1G
      accessmode: ReadWriteOnce
      storagetype: dynamic
      storageclass: ""
      #      matchLabels: ""
      #    storages:
      #      my-gcs:
      #        type: gcs
      #        bucket: some-gcs-bucket
      #    repoPath: ""
    schedule:
      - name: "sat-night-backup"
        schedule: "0 0 * * 6"
        keep: 3
        type: full
        storage: local
  pgBouncer:
    image: percona/percona-postgresql-operator:1.3.0-ppg14-pgbouncer
    #    imagePullPolicy: Always
    size: 1
    resources:
      requests:
        cpu: "1"
        memory: "128Mi"
        #      limits:
        #        cpu: "2"
        #        memory: "512Mi"
        #    affinity:
        #      antiAffinityType: preferred
    expose:
      serviceType: ClusterIP
      #      loadBalancerSourceRanges:
      #      annotations:
      #        pg-cluster-annot: cluster1
      #      labels:
      #        pg-cluster-label: cluster1
  pgReplicas:
    hotStandby:
      size: 2
      resources:
        requests:
          cpu: "500m"
          memory: "256Mi"
          #        limits:
          #          cpu: "500m"
          #          memory: "256Mi"
      volumeSpec:
        accessmode: ReadWriteOnce
        size: 1G
        storagetype: dynamic
        storageclass: ""
        #        matchLabels: ""
        #      labels:
        #        pg-cluster-label: cluster1
        #      annotations:
        #        pg-cluster-annot: cluster1-1
      enableSyncStandby: false
      expose:
        serviceType: ClusterIP
        #        loadBalancerSourceRanges:
        #        annotations:
        #          pg-cluster-annot: cluster1
        #        labels:
        #          pg-cluster-label: cluster1
  pgBadger:
    enabled: true
    image: percona/percona-postgresql-operator:1.3.0-ppg14-pgbadger
    #    imagePullPolicy: Always
    port: 10000
#  securityContext:
#    fsGroup: 1001
#    supplementalGroups: [1001, 1002, 1003]
