#!/bin/bash

set -o errexit
set -o xtrace

TARGET_IMAGE_OPERATOR=${IMAGE_OPERATOR}
TARGET_IMAGE_DEPLOYER=${IMAGE_DEPLOYER}
TARGET_IMAGE_PGBOUNCER=${IMAGE_PGBOUNCER}
TARGET_IMAGE_PG_HA=${IMAGE_PG_HA}
TARGET_IMAGE_BACKREST=${IMAGE_BACKREST}
TARGET_IMAGE_BACKREST_REPO=${IMAGE_BACKREST_REPO}
TARGET_IMAGE_PGBADGER=${IMAGE_PGBADGER}

test_dir=$(realpath $(dirname $0))
. "${test_dir}"/../functions

main() {
	IMAGE_OPERATOR="percona/percona-postgresql-operator:0.2.0-postgres-operator"
	IMAGE_DEPLOYER="percona/percona-postgresql-operator:0.2.0-pgo-deployer"

	IMAGE_PGBOUNCER="percona/percona-postgresql-operator:0.2.0-ppg13-pgbouncer"
	IMAGE_PG_HA="percona/percona-postgresql-operator:0.2.0-ppg13-postgres-ha"
	IMAGE_BACKREST="percona/percona-postgresql-operator:0.2.0-ppg13-pgbackrest"
	IMAGE_BACKREST_REPO="percona/percona-postgresql-operator:0.2.0-ppg13-pgbackrest-repo"
	IMAGE_PGBADGER="percona/percona-postgresql-operator:0.2.0-ppg13-pgbadger"

	create_namespace $namespace

	deploy_operator '' "${test_dir}/conf/0.2.0_operator.yaml"

	desc 'start cluster'
	cluster="some-name"
	kubectl_bin apply -f $conf_dir/client.yml

	spinup_pgcluster "${cluster}" "${test_dir}/conf/0.2.0_cr.yaml"
	wait_job_completion "backrest-backup-${cluster}"

	kubectl_bin patch "perconapgcluster/${cluster}" --type json -p \
		'[
			{"op":"replace","path":"/spec/pause","value":true},
			{"op":"replace","path":"/spec/pgBouncer/size","value":0},
		]'
	wait_cluster_status "${cluster}" "pgcluster Shutdown"

	kubectl_bin delete \
		serviceaccounts/pgo-deployer-sa \
		clusterroles/pgo-deployer-cr \
		configmaps/pgo-deployer-cm \
		configmaps/pgo-config \
		clusterrolebindings/pgo-deployer-crb \
		jobs.batch/pgo-deploy \
		deployment/postgres-operator

	IMAGE_OPERATOR="${TARGET_IMAGE_OPERATOR:-"perconalab/percona-postgresql-operator:${GIT_BRANCH}-postgres-operator"}"
	IMAGE_DEPLOYER="${TARGET_IMAGE_DEPLOYER:-"perconalab/percona-postgresql-operator:${GIT_BRANCH}-pgo-deployer"}"

	IMAGE_PGBOUNCER="${TARGET_IMAGE_PGBOUNCER:-"perconalab/percona-postgresql-operator:1.0.0-ppg13-pgbouncer"}"
	IMAGE_PG_HA="${TARGET_IMAGE_PG_HA:-"perconalab/percona-postgresql-operator:1.0.0-ppg13-postgres-ha"}"
	IMAGE_BACKREST="${TARGET_IMAGE_BACKREST:-"perconalab/percona-postgresql-operator:1.0.0-ppg13-pgbackrest"}"
	IMAGE_BACKREST_REPO="${TARGET_IMAGE_BACKREST_REPO:-"perconalab/percona-postgresql-operator:1.0.0-ppg13-pgbackrest-repo"}"
	IMAGE_PGBADGER="${TARGET_IMAGE_PGBADGER:-"perconalab/percona-postgresql-operator:1.0.0-ppg13-pgbadger"}"

	deploy_operator

	kubectl_bin patch "perconapgcluster/${cluster}" --type json -p \
		'[
			{"op":"replace","path":"/spec/backup/backrestRepoImage","value":'${IMAGE_BACKREST_REPO}'},
			{"op":"replace","path":"/spec/backup/image","value":'${IMAGE_BACKREST}'},
			{"op":"replace","path":"/spec/pgBadger/image","value":'${IMAGE_PGBADGER}'},
			{"op":"replace","path":"/spec/pgBouncer/image","value":'${IMAGE_PGBOUNCER}'},
			{"op":"replace","path":"/spec/pgPrimary/image","value":'${IMAGE_PG_HA}'},
			{"op":"replace","path":"/spec/userLabels/pgo-version","value":'${GIT_BRANCH}'},
			{"op":"replace","path":"/metadata/labels/pgo-version","value":'${GIT_BRANCH}'},
			{"op":"replace","path":"/spec/pause","value":false}
		]'

	wait_cluster_consistency "${cluster}"
	wait_deployment "${cluster}"
	# wait for some significant time period. Pgbouncer pod may not be started otherwise
	sleep 120
	kubectl_bin patch "perconapgcluster/${cluster}" --type json -p \
		'[
			{"op":"replace","path":"/spec/pgBouncer/size","value":1}
		]'
	wait_cluster_consistency "${cluster}"
	wait_deployment "${cluster}-pgbouncer"

	kubectl_bin patch "perconapgcluster/${cluster}" --type json -p \
		'[
			{"op":"replace","path":"/spec/pause","value":true},
			{"op":"replace","path":"/spec/pgBouncer/size","value":0},
		]'
	wait_cluster_status "${cluster}" "pgcluster Shutdown"

	kubectl_bin delete \
		serviceaccounts/pgo-deployer-sa \
		clusterroles/pgo-deployer-cr \
		configmaps/pgo-deployer-cm \
		configmaps/pgo-config \
		clusterrolebindings/pgo-deployer-crb \
		jobs.batch/pgo-deploy \
		deployment/postgres-operator

	IMAGE_OPERATOR="${TARGET_IMAGE_OPERATOR:-"perconalab/percona-postgresql-operator:${GIT_BRANCH}-postgres-operator"}"
	IMAGE_DEPLOYER="${TARGET_IMAGE_DEPLOYER:-"perconalab/percona-postgresql-operator:${GIT_BRANCH}-pgo-deployer"}"

	IMAGE_PGBOUNCER="${TARGET_IMAGE_PGBOUNCER:-"perconalab/percona-postgresql-operator:main-ppg13-pgbouncer"}"
	IMAGE_PG_HA="${TARGET_IMAGE_PG_HA:-"perconalab/percona-postgresql-operator:main-ppg13-postgres-ha"}"
	IMAGE_BACKREST="${TARGET_IMAGE_BACKREST:-"perconalab/percona-postgresql-operator:main-ppg13-pgbackrest"}"
	IMAGE_BACKREST_REPO="${TARGET_IMAGE_BACKREST_REPO:-"perconalab/percona-postgresql-operator:main-ppg13-pgbackrest-repo"}"
	IMAGE_PGBADGER="${TARGET_IMAGE_PGBADGER:-"perconalab/percona-postgresql-operator:main-ppg13-pgbadger"}"

	deploy_operator

	kubectl_bin patch "perconapgcluster/${cluster}" --type json -p \
		'[
			{"op":"replace","path":"/spec/backup/backrestRepoImage","value":'${IMAGE_BACKREST_REPO}'},
			{"op":"replace","path":"/spec/backup/image","value":'${IMAGE_BACKREST}'},
			{"op":"replace","path":"/spec/pgBadger/image","value":'${IMAGE_PGBADGER}'},
			{"op":"replace","path":"/spec/pgBouncer/image","value":'${IMAGE_PGBOUNCER}'},
			{"op":"replace","path":"/spec/pgPrimary/image","value":'${IMAGE_PG_HA}'},
			{"op":"replace","path":"/spec/userLabels/pgo-version","value":'${GIT_BRANCH}'},
			{"op":"replace","path":"/metadata/labels/pgo-version","value":'${GIT_BRANCH}'},
			{"op":"replace","path":"/spec/pause","value":false}
		]'

	wait_cluster_consistency "${cluster}"
	wait_deployment "${cluster}"
	# wait for some significant time period. Pgbouncer pod may not be started otherwise
	sleep 180
	kubectl_bin patch "perconapgcluster/${cluster}" --type json -p \
		'[
			{"op":"replace","path":"/spec/pgBouncer/size","value":1}
		]'
	wait_cluster_consistency "${cluster}"
	wait_deployment "${cluster}-pgbouncer"

	compare_psql_cmd "select-1" '\c myapp \\\ SELECT * from myApp;' "${cluster}:${cluster}_pass@${cluster}-pgbouncer.${namespace}"

	backup_time_interval_min=5
	kubectl_bin patch "perconapgcluster/${cluster}" --type json -p \
		'[
			{"op":"add","path":"/spec/backup/schedule","value":[{"name":"5min-backup","schedule":"*/'${backup_time_interval_min}' * * * *","keep":3,"type":"full","storage":"local"}]},
			{"op":"add","path":"/spec/backup/storages","value":{"local":{"type":"local"}}}
		]'
	sleep 10
	configmap_creation_time=$(kubectl_bin get configmap/${cluster}-${backup_time_interval_min}min-backup -o jsonpath='{.metadata.creationTimestamp}')
	backup_target_minute=$(($(($($date -d${configmap_creation_time} +%M) + ${backup_time_interval_min})) - $(($(($($date -d${configmap_creation_time} +%M) + ${backup_time_interval_min})) % ${backup_time_interval_min}))))
	sleep_time=$(($((${backup_target_minute} - $($date +%M))) * 60))
	sleep ${sleep_time}

	backup_job=$(kubectl_bin get jobs --selector=backrest-command=backup,pg-cluster=${cluster} | grep sch | awk '{print $1}')
	wait_job_completion ${backup_job}

	compare_psql_cmd "select-1" '\c myapp \\\ SELECT * from myApp;' "${cluster}:${cluster}_pass@${cluster}-pgbouncer.${namespace}"

	kubectl create secret generic ${cluster}-ssl-ca --from-file=ca.crt=${conf_dir}/ca.crt
	kubectl create secret tls ${cluster}-ssl-keypair --cert=${conf_dir}/server.crt --key=${conf_dir}/server.key
	kubectl_bin delete -f ${conf_dir}/client.yml
	kubectl_bin apply -f ${test_dir}/conf/client.yml
	kubectl_bin patch "perconapgcluster/${cluster}" --type json -p \
		'[
			{"op":"add","path":"/spec/tlsOnly","value":true},
			{"op":"add","path":"/spec/sslCA","value":'"'${cluster}-ssl-ca'"'},
			{"op":"add","path":"/spec/sslSecretName","value":'"'${cluster}-ssl-keypair'"'},
			{"op":"add","path":"/spec/sslReplicationSecretName","value":'"'${cluster}-ssl-keypair'"'},
		]'
	wait_cluster_consistency "${cluster}"
	wait_deployment "${cluster}"

	kubectl_bin patch "perconapgcluster/${cluster}" --type json -p \
		'[
			{"op":"replace","path":"/spec/pgBouncer/size","value":0}
		]'
	sleep 130
	wait_for_delete "deployment/${cluster}-pgbouncer"

	kubectl_bin patch "perconapgcluster/${cluster}" --type json -p \
		'[
			{"op":"replace","path":"/spec/pgBouncer/size","value":1}
		]'
	wait_deployment "${cluster}-pgbouncer"

	compare_psql "select-1" '\c myapp \\\ SELECT * from myApp;' "${cluster}:${cluster}_pass@${cluster}-pgbouncer.${namespace}" "verify-ca"

	destroy "${namespace}"
}

main
