#!/bin/bash

set -o errexit
set -o xtrace

TARGET_IMAGE_OPERATOR=${IMAGE_OPERATOR}
TARGET_IMAGE_DEPLOYER=${IMAGE_DEPLOYER}
TARGET_IMAGE_PGBOUNCER=${IMAGE_PGBOUNCER}
TARGET_IMAGE_PG_HA=${IMAGE_PG_HA}
TARGET_IMAGE_BACKREST=${IMAGE_BACKREST}
TARGET_IMAGE_BACKREST_REPO=${IMAGE_BACKREST_REPO}
TARGET_IMAGE_PGBADGER=${IMAGE_PGBADGER}

test_dir=$(realpath $(dirname $0))
. "${test_dir}"/../functions

main() {

	create_namespace $namespace
	cluster="some-name"

	if [[ "${PG_VER}" -le '13' ]]; then
		PGO_TAG='0.2.0'

		IMAGE_OPERATOR="percona/percona-postgresql-operator:$PGO_TAG-postgres-operator"
		IMAGE_DEPLOYER="percona/percona-postgresql-operator:$PGO_TAG-pgo-deployer"

		IMAGE_PGBOUNCER="percona/percona-postgresql-operator:$PGO_TAG-ppg$PG_VER-pgbouncer"
		IMAGE_PG_HA="percona/percona-postgresql-operator:$PGO_TAG-ppg$PG_VER-postgres-ha"
		IMAGE_BACKREST="percona/percona-postgresql-operator:$PGO_TAG-ppg$PG_VER-pgbackrest"
		IMAGE_BACKREST_REPO="percona/percona-postgresql-operator:$PGO_TAG-ppg$PG_VER-pgbackrest-repo"
		IMAGE_PGBADGER="percona/percona-postgresql-operator:$PGO_TAG-ppg$PG_VER-pgbadger"

		deploy_operator '' "${test_dir}/conf/0.2.0_operator.yaml"

		desc 'start cluster'
		cluster="some-name"
		kubectl_bin apply -f $conf_dir/client.yml

		create_user_secrets "${cluster}"
		spinup_pgcluster "${cluster}" "${test_dir}/conf/0.2.0_cr.yaml"
		wait_job_completion "backrest-backup-${cluster}"

		kubectl_bin patch "perconapgcluster/${cluster}" --type json -p \
			'[
				{"op":"replace","path":"/spec/pause","value":true},
				{"op":"replace","path":"/spec/pgBouncer/size","value":0},
			]'
		wait_cluster_status "${cluster}" "pgcluster Shutdown"

		kubectl_bin delete \
			serviceaccounts/pgo-deployer-sa \
			clusterroles/pgo-deployer-cr \
			configmaps/pgo-deployer-cm \
			configmaps/pgo-config \
			clusterrolebindings/pgo-deployer-crb \
			jobs.batch/pgo-deploy \
			deployment/postgres-operator \
			deployment/some-name-pgbouncer \
			service/some-name-pgbouncer || :
	fi

	PGO_TAG='1.0.0'
	IMAGE_OPERATOR="perconalab/percona-postgresql-operator:${PGO_TAG}-postgres-operator"
	IMAGE_DEPLOYER="perconalab/percona-postgresql-operator:${PGO_TAG}-pgo-deployer"

	IMAGE_PGBOUNCER="perconalab/percona-postgresql-operator:$PGO_TAG-ppg$PG_VER-pgbouncer"
	IMAGE_PG_HA="perconalab/percona-postgresql-operator:$PGO_TAG-ppg$PG_VER-postgres-ha"
	IMAGE_BACKREST="perconalab/percona-postgresql-operator:$PGO_TAG-ppg$PG_VER-pgbackrest"
	IMAGE_BACKREST_REPO="perconalab/percona-postgresql-operator:$PGO_TAG-ppg$PG_VER-pgbackrest-repo"
	IMAGE_PGBADGER="perconalab/percona-postgresql-operator:$PGO_TAG-ppg$PG_VER-pgbadger"

	deploy_operator
	if [[ "${PG_VER}" -ge '14' ]]; then
		desc 'start cluster'
		create_user_secrets "${cluster}"
		spinup_pgcluster "${cluster}" "${src_dir}/deploy/cr.yaml"
	else
		kubectl_bin patch "perconapgcluster/${cluster}" --type json -p \
			'[
				{"op":"replace","path":"/spec/backup/backrestRepoImage","value":'${IMAGE_BACKREST_REPO}'},
				{"op":"replace","path":"/spec/backup/image","value":'${IMAGE_BACKREST}'},
				{"op":"replace","path":"/spec/pgBadger/image","value":'${IMAGE_PGBADGER}'},
				{"op":"replace","path":"/spec/pgBouncer/image","value":'${IMAGE_PGBOUNCER}'},
				{"op":"replace","path":"/spec/pgPrimary/image","value":'${IMAGE_PG_HA}'},
				{"op":"replace","path":"/spec/userLabels/pgo-version","value":'${PGO_TAG}'},
				{"op":"replace","path":"/metadata/labels/pgo-version","value":'${PGO_TAG}'},
				{"op":"replace","path":"/spec/pause","value":false}
			]'
	fi

	wait_cluster_consistency "${cluster}"
	wait_deployment "${cluster}"
	# wait for some significant time period. Pgbouncer pod may not be started otherwise
	sleep 10
	if [[ "${PG_VER}" -le '13' ]]; then
		kubectl_bin patch "perconapgcluster/${cluster}" --type json -p \
			'[
				{"op":"replace","path":"/spec/pgBouncer/size","value":1}
			]'
	fi
	wait_cluster_consistency "${cluster}"
	wait_deployment "${cluster}-pgbouncer"

	kubectl_bin patch "perconapgcluster/${cluster}" --type json -p \
		'[
			{"op":"replace","path":"/spec/pause","value":true},
			{"op":"replace","path":"/spec/pgBouncer/size","value":0},
		]'
	wait_cluster_status "${cluster}" "pgcluster Shutdown"

	kubectl_bin delete \
		serviceaccounts/pgo-deployer-sa \
		clusterroles/pgo-deployer-cr \
		configmaps/pgo-deployer-cm \
		configmaps/pgo-config \
		clusterrolebindings/pgo-deployer-crb \
		jobs.batch/pgo-deploy \
		deployment/postgres-operator \
		deployment/some-name-pgbouncer \
		service/some-name-pgbouncer || :

	IMAGE_OPERATOR="${TARGET_IMAGE_OPERATOR:-"perconalab/percona-postgresql-operator:${GIT_BRANCH}-postgres-operator"}"
	IMAGE_DEPLOYER="${TARGET_IMAGE_DEPLOYER:-"perconalab/percona-postgresql-operator:${GIT_BRANCH}-pgo-deployer"}"

	IMAGE_PGBOUNCER="${TARGET_IMAGE_PGBOUNCER:-"perconalab/percona-postgresql-operator:main-ppg$PG_VER-pgbouncer"}"
	IMAGE_PG_HA="${TARGET_IMAGE_PG_HA:-"perconalab/percona-postgresql-operator:main-ppg$PG_VER-postgres-ha"}"
	IMAGE_BACKREST="${TARGET_IMAGE_BACKREST:-"perconalab/percona-postgresql-operator:main-ppg$PG_VER-pgbackrest"}"
	IMAGE_BACKREST_REPO="${TARGET_IMAGE_BACKREST_REPO:-"perconalab/percona-postgresql-operator:main-ppg$PG_VER-pgbackrest-repo"}"
	IMAGE_PGBADGER="${TARGET_IMAGE_PGBADGER:-"perconalab/percona-postgresql-operator:main-ppg$PG_VER-pgbadger"}"

	deploy_operator

	kubectl_bin patch "perconapgcluster/${cluster}" --type json -p \
		'[
			{"op":"replace","path":"/spec/backup/backrestRepoImage","value":'${IMAGE_BACKREST_REPO}'},
			{"op":"replace","path":"/spec/backup/image","value":'${IMAGE_BACKREST}'},
			{"op":"replace","path":"/spec/pgBadger/image","value":'${IMAGE_PGBADGER}'},
			{"op":"replace","path":"/spec/pgBouncer/image","value":'${IMAGE_PGBOUNCER}'},
			{"op":"replace","path":"/spec/pgPrimary/image","value":'${IMAGE_PG_HA}'},
			{"op":"replace","path":"/spec/userLabels/pgo-version","value":'${GIT_BRANCH}'},
			{"op":"replace","path":"/metadata/labels/pgo-version","value":'${GIT_BRANCH}'},
			{"op":"replace","path":"/spec/pause","value":false}
		]'

	wait_cluster_consistency "${cluster}"
	wait_deployment "${cluster}"
	# wait for some significant time period. Pgbouncer pod may not be started otherwise
	sleep 10
	kubectl_bin patch "perconapgcluster/${cluster}" --type json -p \
		'[
			{"op":"replace","path":"/spec/pgBouncer/size","value":1}
		]'
	wait_cluster_consistency "${cluster}"
	wait_deployment "${cluster}-pgbouncer"

	sleep 10
	compare_psql_cmd "select-1" '\c myapp \\\ SELECT * from myApp;' "${cluster}:${cluster}_pass@${cluster}-pgbouncer.${namespace}"

	backup_time_interval_min=5
	kubectl_bin patch "perconapgcluster/${cluster}" --type json -p \
		'[
			{"op":"add","path":"/spec/backup/schedule","value":[{"name":"5min-backup","schedule":"*/'${backup_time_interval_min}' * * * *","keep":3,"type":"full","storage":"local"}]},
			{"op":"add","path":"/spec/backup/storages","value":{"local":{"type":"local"}}}
		]'
	sleep 10
	configmap_creation_time=$(kubectl_bin get configmap/${cluster}-${backup_time_interval_min}min-backup -o jsonpath='{.metadata.creationTimestamp}')
	backup_target_minute=$(($(($($date -d${configmap_creation_time} +%M) + ${backup_time_interval_min})) - $(($(($($date -d${configmap_creation_time} +%M) + ${backup_time_interval_min})) % ${backup_time_interval_min}))))
	sleep_time=$(($((${backup_target_minute} - $($date +%M))) * 60))
	sleep ${sleep_time}

	backup_job=$(kubectl_bin get jobs --selector=backrest-command=backup,pg-cluster=${cluster} | grep sch | awk '{print $1}')
	wait_job_completion ${backup_job}

	compare_psql_cmd "select-1" '\c myapp \\\ SELECT * from myApp;' "${cluster}:${cluster}_pass@${cluster}-pgbouncer.${namespace}"

	kubectl create secret generic ${cluster}-ssl-ca --from-file=ca.crt=${conf_dir}/ca.crt
	kubectl create secret tls ${cluster}-ssl-keypair --cert=${conf_dir}/server.crt --key=${conf_dir}/server.key
	kubectl_bin delete -f ${conf_dir}/client.yml
	kubectl_bin apply -f ${test_dir}/conf/client.yml
	kubectl_bin patch "perconapgcluster/${cluster}" --type json -p \
		'[
			{"op":"add","path":"/spec/tlsOnly","value":true},
			{"op":"add","path":"/spec/sslCA","value":'"'${cluster}-ssl-ca'"'},
			{"op":"add","path":"/spec/sslSecretName","value":'"'${cluster}-ssl-keypair'"'},
			{"op":"add","path":"/spec/sslReplicationSecretName","value":'"'${cluster}-ssl-keypair'"'},
		]'
	wait_cluster_consistency "${cluster}"
	wait_deployment "${cluster}"

	kubectl_bin patch "perconapgcluster/${cluster}" --type json -p \
		'[
			{"op":"replace","path":"/spec/pgBouncer/size","value":0}
		]'
	sleep 10
	wait_for_delete "deployment/${cluster}-pgbouncer"

	kubectl_bin patch "perconapgcluster/${cluster}" --type json -p \
		'[
			{"op":"replace","path":"/spec/pgBouncer/size","value":1}
		]'
	wait_deployment "${cluster}-pgbouncer"
	sleep 10
	compare_psql "select-1" '\c myapp \\\ SELECT * from myApp;' "${cluster}:${cluster}_pass@${cluster}-pgbouncer.${namespace}" "verify-ca"

	destroy "${namespace}"
}

main
