apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  labels:
    postgres-operator.crunchydata.com/role: pgadmin
    postgres-operator.crunchydata.com/pgadmin: pgadmin
  ownerReferences:
  - apiVersion: postgres-operator.crunchydata.com/v1beta1
    controller: true
    kind: PGAdmin
    name: pgadmin
spec:
  selector:
    postgres-operator.crunchydata.com/pgadmin: pgadmin
  ports:
  - port: 5050
    targetPort: 5050
    protocol: TCP
    name: pgadmin-port
  type: ClusterIP
