#!/bin/bash

set -o errexit
set -o xtrace

test_dir=$(realpath $(dirname $0))
. ${test_dir}/../functions

create_namespace $namespace
deploy_operator
cluster="some-name"

spinup_pgcluster "${cluster}" "${src_dir}/deploy/cr.yaml"
compare_psql_cmd "show-1" 'SHOW DATABASES' "pgbouncer:$(get_psql_user_pass pgbouncer ${cluster})@${cluster}-pgbouncer.${namespace}"
compare_psql_cmd "select-1" '\c myapp \\\ SELECT * from myApp;' "postgres:$(get_psql_user_pass postgres ${cluster})@${cluster}.${namespace}"

newpass="test-password"
newpassencrypted=$(echo -n "$newpass" | base64)
secret_name='some-name-users-secret'
patch_secret "$secret_name" "postgres" "$newpassencrypted"
sleep 15
compare_psql_cmd "select-1" '\c myapp \\\ SELECT * from myApp;' "postgres:${newpass}@${cluster}.${namespace}"

patch_secret "$secret_name" "some-name" "$newpassencrypted"
sleep 15
compare_psql_cmd "select-1" '\c myapp \\\ SELECT * from myApp;' "some-name:${newpass}@${cluster}.${namespace}"

patch_secret "$secret_name" "pgbouncer" "$newpassencrypted"
sleep 60
compare_psql_cmd "show-1" 'SHOW DATABASES' "pgbouncer:${newpass}@${cluster}-pgbouncer.${namespace}"

kubectl_bin patch "perconapgcluster/${cluster}" --type json -p \
		'[
			{"op":"replace","path":"/spec/pgBouncer/size","value":0}
		]'
sleep 30

desc "restart bouncer to check if password didn't changed"
kubectl_bin patch "perconapgcluster/${cluster}" --type json -p \
		'[
			{"op":"replace","path":"/spec/pgBouncer/size","value":3}
		]'
sleep 60
compare_psql_cmd "show-1" 'SHOW DATABASES' "pgbouncer:${newpass}@${cluster}-pgbouncer.${namespace}"

destroy "${namespace}"
