apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  labels:
    name: some-name-pgbouncer
    pg-cluster: some-name
  name: some-name-pgbouncer
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    service-name: some-name-pgbouncer
  sessionAffinity: None
  type: LoadBalancer
