apiVersion: v1
kind: Service
metadata:
  labels:
    crunchy-pgha-scope: some-name
    deployment-name: some-name
    name: some-name-pgbouncer
    pg-cluster: some-name
    pgouser: admin
    vendor: crunchydata
  name: some-name-pgbouncer
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    service-name: some-name-pgbouncer
  sessionAffinity: None
  type: LoadBalancer
