apiVersion: v1
kind: Service
metadata:
  labels:
    name: some-name
    pg-cluster: some-name
  name: some-name
spec:
  ports:
    - name: sshd
      port: 2022
      protocol: TCP
      targetPort: 2022
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    pg-cluster: some-name
    role: master
  sessionAffinity: None
  type: ClusterIP
