apiVersion: pgv2.percona.com/v2
kind: PerconaPGCluster
metadata:
  name: example
spec:
  image: perconalab/percona-postgresql-operator:main-ppg15-postgres
  imagePullPolicy: Always
  postgresVersion: 15
  instances:
  - name: instance1
    dataVolumeClaimSpec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
  proxy:
    pgBouncer:
      image: perconalab/percona-postgresql-operator:main-ppg15-pgbouncer
  backups:
    pgbackrest:
      image: perconalab/percona-postgresql-operator:main-ppg15-pgbackrest
      manual:
        repoName: repo1
        options:
         - --type=full
      repos:
      - name: repo1
        schedules:
          full: "0 0 * * 6"
        volume:
          volumeClaimSpec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
  pmm:
    enabled: false
    image: percona/pmm-client:2.32.0
    secret: example-pmm-secret
    serverHost: monitoring-service