---
apiVersion: kuttl.dev/v1beta1
kind: TestStep
commands:
  - script: |
      set -e

      PRIMARY=$(
        kubectl get pod --namespace "${NAMESPACE}" \
          --output name --selector \
          'postgres-operator.crunchydata.com/cluster=ldap,postgres-operator.crunchydata.com/role=master' \
          | head -1
      )

      echo "Primary pod: ${PRIMARY}"

      # Verify pg_hba.conf contains the LDAP rule.
      HBA=$(kubectl exec --namespace "${NAMESPACE}" "${PRIMARY}" -c database \
        -- psql -tAc "SELECT pg_read_file('pg_hba.conf');" 2>&1)
      echo "--- pg_hba.conf ---"
      echo "${HBA}"
      echo "-------------------"

      contains() { bash -ceu '[[ "$1" == *"$2"* ]]' - "$@"; }
      contains "${HBA}" "ldap" || {
        echo >&2 'pg_hba.conf does not contain an ldap rule'
        exit 1
      }

      # Verify the LDAP entries were added by the setup container.
      # Retry to account for the 60-second sleep before ldapadd runs.
      echo "Verifying LDAP directory entries..."
      for i in $(seq 12); do
        if kubectl exec --namespace "${NAMESPACE}" deployment/openldap -c ldap-setup \
          -- ldapsearch -x -H ldap://localhost:389 \
             -D "cn=admin,dc=ldap,dc=local" -w adminpassword \
             -b "uid=percona,ou=perconadba,dc=ldap,dc=local" 2>&1 \
          | grep -q "uid: percona"; then
          echo "LDAP entry for percona found"
          break
        fi
        echo "Attempt ${i}: LDAP entry not yet available, waiting..."
        sleep 10
      done

      # Test LDAP authentication: connect as the percona user via TCP.
      # The pg_hba.conf rule uses simple bind:
      #   uid={username},ou=perconadba,dc=ldap,dc=local  →  password: "password"
      # PGSSLMODE=disable forces a plain TCP connection (matches the "host" rule).
      echo "Testing LDAP authentication..."
      result=""
      for i in $(seq 6); do
        result=$(kubectl exec --namespace "${NAMESPACE}" "${PRIMARY}" -c database \
          -- bash -c 'PGPASSWORD=password PGSSLMODE=disable \
            psql -h 127.0.0.1 -U percona -d percona -tAc "SELECT current_user;" 2>&1') && break
        echo "Attempt ${i} failed: ${result}"
        sleep 10
      done

      echo "Result: ${result}"
      [[ "${result}" == "percona" ]] || {
        echo >&2 "Expected current_user='percona', got: ${result}"
        exit 1
      }

      echo "LDAP authentication test passed"
