# https://golangci-lint.run/usage/configuration/

linters:
  disable:
    - gofumpt
    - scopelint
  enable:
    - gosimple
    - misspell
  presets:
    - bugs
    - format
    - unused

linters-settings:
  exhaustive:
    default-signifies-exhaustive: true
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/percona)

run:
  skip-dirs:
    - hack
    - pkg/generated
