# https://golangci-lint.run/usage/configuration/

linters:
  disable:
    - contextcheck
    - errchkjson
    - gci
    - gofumpt
    - scopelint
    - depguard
  enable:
    - gomodguard
    - gosimple
    - importas
    - misspell
    - unconvert
  presets:
    - bugs
    - format
    - unused

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/percona)

  depguard:
    rules:
      main:
        allow:
          - $gostd
          - github.com/OpenPeeDeeP
    include-go-root: true
    packages-with-error-message:
      - io/ioutil: >
          Use the "io" and "os" packages instead.
          See https://go.dev/doc/go1.16#ioutil

      - net/http/httptest: Should be used only in tests.
      - testing/*: The "testing" packages should be used only in tests.

      - github.com/percona/percona-postgresql-operator/internal/testing/*: >
          The "internal/testing" packages should be used only in tests.

  exhaustive:
    default-signifies-exhaustive: true

  goimports:
    local-prefixes: github.com/percona/percona-postgresql-operator

  gomodguard:
    blocked:
      modules:
        - gopkg.in/yaml.v2: { recommendations: [sigs.k8s.io/yaml] }
        - gopkg.in/yaml.v3: { recommendations: [sigs.k8s.io/yaml] }
        - gotest.tools: { recommendations: [gotest.tools/v3] }
        - k8s.io/kubernetes:
            reason: >
              k8s.io/kubernetes is for managing dependencies of the Kubernetes
              project, i.e. building kubelet and kubeadm.

  importas:
    alias:
      - pkg: k8s.io/api/(\w+)/(v[\w\w]+)
        alias: $1$2
      - pkg: k8s.io/apimachinery/pkg/apis/(\w+)/(v[\w\d]+)
        alias: $1$2
      - pkg: k8s.io/apimachinery/pkg/api/errors
        alias: k8serrors
    no-unaliased: true

issues:
  exclude-rules:
    # These testing packages are allowed in test files. The packages are
    # disallowed everywhere then ignored here because that is how depguard works.
    - linters: [depguard]
      path: _test[.]go$
      text: \`(net/http/httptest|[^`]*testing[^`]*)`

run:
  build-tags:
    - envtest
  skip-dirs:
    - pkg/generated
    - hack
