apiVersion: pg.percona.com/v1
kind: PerconaPGCluster
metadata:
  annotations:
    current-primary: cluster1
  labels:
    crunchy-pgha-scope: cluster1
    deployment-name: cluster1
    name: cluster1
    pg-cluster: cluster1
    pgo-version: 0.2.0
    pgouser: admin
    role: master
  name: cluster1
spec:
  database: pgdb
  namespace: pgo
  port: "5432"
  user: pguser
  userLabels:
    pgo-version: "0.2.0"
  pgPrimary:
    image: perconalab/percona-postgresql-operator:main-ppg13-postgres-ha
    resources:
        requests:
          memory: "128Mi"
    tolerations: []
  pmm:
    enabled: false
    image: percona/pmm-client:2.15.1
    serverHost: monitoring-service
    serverUser: admin
    pmmSecret: cluster1-pmm-secret
  backup:
    image: perconalab/percona-postgresql-operator:main-ppg13-pgbackrest
    backrestRepoImage: perconalab/percona-postgresql-operator:main-ppg13-pgbackrest-repo
    resources:
        requests:
          memory: "48Mi"
        limits: {}
  pgBouncer:
    image: perconalab/percona-postgresql-operator:main-ppg13-pgbouncer
    size: 1
    resources:
        requests:
          cpu: "1"
          memory: "128Mi"
        limits:
          cpu: "2"
          memory: "512Mi"
  pgReplicas:
    hotStandby:
      size: 3
#      resources:
#        requests:
#          cpu: "1"
#          memory: "128Mi"
#        limits:
#          cpu: "1"
#          memory: "128Mi"
      volumeSpec: 
        accessmode: ReadWriteOnce
        matchLabels: ""
        size: 1G
        storageclass: ""
        storagetype: dynamic
        supplementalgroups: ""
#      affinity:
#        default: null
#      labels:
#        pg-cluster-label: cluster1
#      annotations:
#        pg-cluster-annot: cluster1-1
#      enableSyncStandby: false
      expose:
        serviceType: ClusterIP
#        loadBalancerSourceRanges:
#        annotations:
#          pg-cluster-annot: cluster1
#        labels: 
#          pg-cluster-label: cluster1
