apiVersion: pg.percona.com/v1
kind: PerconaPGCluster
metadata:
  annotations:
    current-primary: cluster1
  labels:
    crunchy-pgha-scope: cluster1
    deployment-name: cluster1
    name: cluster1
    pg-cluster: cluster1
    pgo-version: 1.5.0
    pgouser: admin
  name: cluster1
spec:
  database: pgdb
  port: "5432"
  user: pguser
  disableAutofail: false
  tlsOnly: false
  standby: false
  pause: false
#  sslCA: cluster1-ssl-ca
#  sslSecretName: cluster1-ssl-keypair
#  sslReplicationSecretName: cluster1-ssl-keypair
#  keepData: true
#  keepBackups: true
#  pgDataSource:
#    restoreFrom: ""
#    restoreOpts: ""
#  tablespaceStorages:
#    lake:
#      volumeSpec:
#        size: 1G
#        accessmode: ReadWriteOnce
#        storagetype: dynamic
#        storageclass: ""
#        matchLabels: ""
#  walStorage:
#    volumeSpec:
#      size: 1G
#      accessmode: ReadWriteOnce
#      storagetype: dynamic
#      storageclass: ""
#      matchLabels: ""
  userLabels:
    pgo-version: "main"
  pgPrimary:
    image: perconalab/percona-postgresql-operator:main-ppg13-postgres-ha
    resources:
      requests:
        memory: "128Mi"
    tolerations: []
    volumeSpec:
      size: 1G
      accessmode: ReadWriteOnce
      storagetype: dynamic
      storageclass: ""
#      matchLabels: ""
    expose:
      serviceType: ClusterIP
#      loadBalancerSourceRanges:
#      annotations:
#        pg-cluster-annot: cluster1
#      labels:
#        pg-cluster-label: cluster1
#    customconfig: ""
  pmm:
    enabled: false
    image: percona/pmm-client:2.21.0
    serverHost: monitoring-service
    serverUser: admin
    pmmSecret: cluster1-pmm-secret
    resources:
      requests:
        memory: 200M
        cpu: 500m
#      limits:
#        cpu: "1"
#        memory: "400M"
  backup:
    image: perconalab/percona-postgresql-operator:main-ppg13-pgbackrest
    backrestRepoImage: perconalab/percona-postgresql-operator:main-ppg13-pgbackrest-repo
    resources:
      requests:
        memory: "48Mi"
#      limits:
#        cpu: "1"
#        memory: "64Mi"
    volumeSpec:
      size: 1G
      accessmode: ReadWriteOnce
      storagetype: dynamic
      storageclass: ""
#      matchLabels: ""
#    storages:
#      my-gcs:
#        type: gcs
#        bucket: some-gcs-bucket
#    repoPath: ""
    schedule:
      - name: "sat-night-backup"
        schedule: "0 0 * * 6"
        keep: 3
        type: full
        storage: local
  pgBouncer:
    image: perconalab/percona-postgresql-operator:main-ppg13-pgbouncer
    size: 1
    resources:
      requests:
        cpu: "1"
        memory: "128Mi"
      limits:
        cpu: "2"
        memory: "512Mi"
    expose:
      serviceType: ClusterIP
#      loadBalancerSourceRanges:
#      annotations:
#        pg-cluster-annot: cluster1
#      labels:
#        pg-cluster-label: cluster1
  pgReplicas:
    hotStandby:
      size: 2
      resources:
        requests:
#          cpu: "1"
          memory: "128Mi"
#        limits:
#          cpu: "1"
#          memory: "128Mi"
      volumeSpec:
        accessmode: ReadWriteOnce
        size: 1G
        storagetype: dynamic
        storageclass: ""
#        matchLabels: ""
#      affinity:
#        default: null
#      labels:
#        pg-cluster-label: cluster1
#      annotations:
#        pg-cluster-annot: cluster1-1
      enableSyncStandby: false
      expose:
        serviceType: ClusterIP
#        loadBalancerSourceRanges:
#        annotations:
#          pg-cluster-annot: cluster1
#        labels:
#          pg-cluster-label: cluster1
  pgBadger:
    enabled: true
    image: perconalab/percona-postgresql-operator:main-ppg13-pgbadger
    port: 10000
#  securityContext:
#    fsGroup: 1001
#    supplementalGroups: [1001, 1002, 1003]
#  upgradeOptions:
#    versionServiceEndpoint: https://check.percona.com
#    apply: recommended
#    schedule: "*/5 * * * *"
