#!/bin/bash

set -o errexit
set -o xtrace


test_dir=$(realpath $(dirname $0))
. "${test_dir}"/../functions

main() {

	create_namespace $namespace
	deploy_operator

	desc 'start cluster'
	cluster="cluster1"
	PGO_TAG='1.0.0'
    PG_VER='13'
	kubectl_bin apply -f $conf_dir/client.yml
    IMAGE_PGBOUNCER="percona/percona-postgresql-operator:$PGO_TAG-ppg$PG_VER-pgbouncer" 
	IMAGE_PG_HA="percona/percona-postgresql-operator:$PGO_TAG-ppg$PG_VER-postgres-ha"
	IMAGE_BACKREST="percona/percona-postgresql-operator:$PGO_TAG-ppg$PG_VER-pgbackrest"
	IMAGE_BACKREST_REPO="percona/percona-postgresql-operator:$PGO_TAG-ppg$PG_VER-pgbackrest-repo"
	IMAGE_PGBADGER="percona/percona-postgresql-operator:$PGO_TAG-ppg$PG_VER-pgbadger"
	spinup_pgcluster "${cluster}" "${test_dir}/conf/1.0.0_cr.yaml"
	wait_job_completion "backrest-backup-${cluster}"
	sleep 30


	kubectl_bin apply -f ${test_dir}/conf/main_cr.yaml
    sleep 60
	wait_cluster_consistency "${cluster}"

	sleep 10
	compare_psql_cmd "show-1" 'SHOW DATABASES' "pgbouncer:pgbouncer_pass@${cluster}-pgbouncer.${namespace}"

	destroy "${namespace}"
}

main
