---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-account-percona-postgresql-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: percona-postgresql-operator
subjects:
- kind: ServiceAccount
  name: percona-postgresql-operator
