apiVersion: v1
kind: Secret
metadata:
  name: minio-gw-gcs-secret
type: Opaque
stringData:
  credentials.json: |
    {
      ...
    }
  MINIO_ROOT_USER: minio_root
  MINIO_ROOT_PASSWORD: minio_password
