apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: minio-gw-tls
spec:
  isCA: true
  commonName: minio-gateway-svc
  secretName: minio-gw-tls
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: minio-gw-tls
spec:
  ca:
    secretName: minio-gw-tls
