---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pgclusters.pg.percona.com
spec:
  group: pg.percona.com
  names:
    kind: Pgcluster
    listKind: PgclusterList
    plural: pgclusters
    singular: pgcluster
  scope: Namespaced
  versions:
  - name: v1
    storage: true
    served: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            x-kubernetes-preserve-unknown-fields: true
            properties:
              clustername: { type: string }
              ccpimage: { type: string }
              ccpimagetag: { type: string }
              database: { type: string }
              exporterport: { type: string }
              name: { type: string }
              pgbadgerport: { type: string }
              port: { type: string }
          status:
            x-kubernetes-preserve-unknown-fields: true
            type: object
            properties:
              state: { type: string }
              message: { type: string }
