---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pgtasks.pg.percona.com
spec:
  conversion:
    strategy: None
  group: pg.percona.com
  names:
    kind: Pgtask
    listKind: PgtaskList
    plural: pgtasks
    singular: pgtask
  scope: Namespaced
  versions:
  - name: v1
    storage: true
    served: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            type: object
            properties:
              state: { type: string }
              message: { type: string }
