apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../default/

patchesStrategicMerge:
- manager-target.yaml

images:
- name: postgres-operator
  newName: asia-south1-docker.pkg.dev/cloud-dev-112233/mayankshah/pg-operator
  newTag: K8SPG-771
