apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: created-without-backups
status:
  instances:
    - name: instance1
  pgbackrest: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    postgres-operator.crunchydata.com/cluster: created-without-backups
    postgres-operator.crunchydata.com/data: postgres
    postgres-operator.crunchydata.com/instance-set: instance1
    postgres-operator.crunchydata.com/role: pgdata
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    postgres-operator.crunchydata.com/cluster: created-without-backups
    postgres-operator.crunchydata.com/data: postgres
    postgres-operator.crunchydata.com/instance-set: instance1
---
apiVersion: v1
kind: Pod
metadata:
  labels:
      postgres-operator.crunchydata.com/cluster: created-without-backups
      postgres-operator.crunchydata.com/data: postgres
      postgres-operator.crunchydata.com/instance-set: instance1
      postgres-operator.crunchydata.com/role: master
status:
  containerStatuses:
  - ready: true
  - ready: true
