blank_issues_enabled: true
contact_links:
  - name: Ask a question about Percona Operator for PostgreSQL or get support
    url: https://forums.percona.com/c/postgresql/percona-kubernetes-operator-for-postgresql/68
    about: Ask a question or request support for using Percona Operator for PostgreSQL
  - name: Report vulnerability or security concern
    url: https://www.percona.com/security
    about: For any security issues or concerns
