// Copyright 2021 - 2024 Crunchy Data Solutions, Inc.
//
// SPDX-License-Identifier: Apache-2.0

package pgbouncer

import (
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"gotest.tools/v3/assert"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/util/intstr"
	"sigs.k8s.io/yaml"

	"github.com/percona/percona-postgresql-operator/v3/internal/testing/cmp"
	"github.com/percona/percona-postgresql-operator/v3/internal/testing/require"
	"github.com/percona/percona-postgresql-operator/v3/pkg/apis/upstream.pgv2.percona.com/v1beta1"
)

func TestPrettyYAML(t *testing.T) {
	b, err := yaml.Marshal(iniValueSet{
		"x": "y",
		"z": "",
	}.String())
	assert.NilError(t, err)
	assert.Assert(t, strings.HasPrefix(string(b), `|`),
		"expected literal block scalar, got:\n%s", b)
}

func TestAuthFileContents(t *testing.T) {
	t.Parallel()

	password := `very"random`
	data, err := authFileContents(password, "", nil)
	assert.NilError(t, err)
	assert.Equal(t, string(data), `"_crunchypgbouncer" "very""random"`+"\n")
}

func TestAuthFileContentsAdminUser(t *testing.T) {
	t.Parallel()

	t.Run("WithAdminPassword", func(t *testing.T) {
		data, err := authFileContents("pgbouncer-password", `admin"password`, nil)
		assert.NilError(t, err)

		assert.Equal(t, string(data), strings.Join([]string{
			`"_crunchypgbouncer" "pgbouncer-password"`,
			`"_crunchypgbounceradmin" "admin""password"`,
			"",
		}, "\n"))
	})

	t.Run("SortedAfterAdminUser", func(t *testing.T) {
		data, err := authFileContents("pgbouncer-password", "admin-password", &corev1.Secret{
			Data: map[string][]byte{
				// Sorts before both operator users, and must still come last.
				"Monitor": []byte("monitor-password"),
			},
		})
		assert.NilError(t, err)

		assert.Equal(t, string(data), strings.Join([]string{
			`"_crunchypgbouncer" "pgbouncer-password"`,
			`"_crunchypgbounceradmin" "admin-password"`,
			`"Monitor" "monitor-password"`,
			"",
		}, "\n"))
	})

	t.Run("ReservedInUserSecret", func(t *testing.T) {
		_, err := authFileContents("pgbouncer-password", "admin-password", &corev1.Secret{
			ObjectMeta: metav1.ObjectMeta{Name: "custom-users"},
			Data: map[string][]byte{
				"_crunchypgbounceradmin": []byte("hijacked"),
			},
		})
		assert.ErrorContains(t, err, `"_crunchypgbounceradmin"`)
		assert.ErrorContains(t, err, "reserved operator user")
	})

	t.Run("NotReservedWhenDisabled", func(t *testing.T) {
		// Below the crVersion gate the operator does not write the admin user,
		// so a user Secret containing that name does not conflict.
		data, err := authFileContents("pgbouncer-password", "", &corev1.Secret{
			ObjectMeta: metav1.ObjectMeta{Name: "custom-users"},
			Data: map[string][]byte{
				"_crunchypgbounceradmin": []byte("their-password"),
			},
		})
		assert.NilError(t, err)

		assert.Equal(t, string(data), strings.Join([]string{
			`"_crunchypgbouncer" "pgbouncer-password"`,
			`"_crunchypgbounceradmin" "their-password"`,
			"",
		}, "\n"))
	})
}

func TestAuthFileContentsUsers(t *testing.T) {
	t.Parallel()

	data, err := authFileContents("pgbouncer-password", "", &corev1.Secret{
		Data: map[string][]byte{
			`stats"user`: []byte(`stats"password`),
			"monitor":    []byte("monitor-password"),
		},
	})
	assert.NilError(t, err)

	assert.Equal(t, string(data), strings.Join([]string{
		`"_crunchypgbouncer" "pgbouncer-password"`,
		`"monitor" "monitor-password"`,
		`"stats""user" "stats""password"`,
		"",
	}, "\n"))
}

func TestEnsureListed(t *testing.T) {
	t.Parallel()

	for _, tt := range []struct {
		name     string
		list     string
		expected string
	}{
		{"Empty", "", "someone"},
		{"OnlySeparators", " , ", "someone"},
		{"Absent", "alice,bob", "alice,bob,someone"},
		{"AbsentKeepsUserFormatting", " alice , bob ", " alice , bob ,someone"},
		{"Present", "alice,someone,bob", "alice,someone,bob"},
		{"PresentWithWhitespace", "alice, someone", "alice, someone"},
		{"NotASubstringMatch", "someone-else", "someone-else,someone"},
	} {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, ensureListed(tt.list, "someone"), tt.expected)
		})
	}
}

func TestClusterINI(t *testing.T) {
	t.Parallel()

	cluster := new(v1beta1.PostgresCluster)
	err := cluster.Default(context.Background(), nil)
	assert.NilError(t, err)

	cluster.Name = "foo-baz"
	*cluster.Spec.Port = 9999

	cluster.Spec.Proxy = new(v1beta1.PostgresProxySpec)
	cluster.Spec.Proxy.PGBouncer = new(v1beta1.PGBouncerPodSpec)
	cluster.Spec.Proxy.PGBouncer.Port = new(int32)
	*cluster.Spec.Proxy.PGBouncer.Port = 8888

	t.Run("Default", func(t *testing.T) {
		assert.Equal(t, clusterINI(cluster), strings.Trim(`
# Generated by postgres-operator. DO NOT EDIT UNLESS YOU KNOW WHAT YOU'RE DOING.
# If you want to override the config, annotate this ConfigMap with pgv2.percona.com/override-config=true

[pgbouncer]
%include /etc/pgbouncer/pgbouncer.ini

[pgbouncer]
auth_file = /etc/pgbouncer/~postgres-operator/users.txt
auth_query = SELECT username, password from pgbouncer.get_auth($1)
auth_user = _crunchypgbouncer
client_tls_ca_file = /etc/pgbouncer/~postgres-operator/frontend-ca.crt
client_tls_cert_file = /etc/pgbouncer/~postgres-operator/frontend-tls.crt
client_tls_key_file = /etc/pgbouncer/~postgres-operator/frontend-tls.key
client_tls_sslmode = require
conffile = /etc/pgbouncer/~postgres-operator.ini
ignore_startup_parameters = extra_float_digits
listen_addr = *
listen_port = 8888
server_tls_ca_file = /etc/pgbouncer/~postgres-operator/backend-ca.crt
server_tls_sslmode = verify-full
unix_socket_dir =

[databases]
* = host=foo-baz-primary port=9999
		`, "\t\n")+"\n")
	})

	t.Run("CustomSettings", func(t *testing.T) {
		cluster.Spec.Proxy.PGBouncer.Config.Global = map[string]string{
			"ignore_startup_parameters": "custom",
			"verbose":                   "whomp",
		}
		cluster.Spec.Proxy.PGBouncer.Config.Databases = map[string]string{
			"appdb": "conn=str",
		}
		cluster.Spec.Proxy.PGBouncer.Config.Users = map[string]string{
			"app": "mode=rad",
		}

		assert.Equal(t, clusterINI(cluster), strings.Trim(`
# Generated by postgres-operator. DO NOT EDIT UNLESS YOU KNOW WHAT YOU'RE DOING.
# If you want to override the config, annotate this ConfigMap with pgv2.percona.com/override-config=true

[pgbouncer]
%include /etc/pgbouncer/pgbouncer.ini

[pgbouncer]
auth_file = /etc/pgbouncer/~postgres-operator/users.txt
auth_query = SELECT username, password from pgbouncer.get_auth($1)
auth_user = _crunchypgbouncer
client_tls_ca_file = /etc/pgbouncer/~postgres-operator/frontend-ca.crt
client_tls_cert_file = /etc/pgbouncer/~postgres-operator/frontend-tls.crt
client_tls_key_file = /etc/pgbouncer/~postgres-operator/frontend-tls.key
client_tls_sslmode = require
conffile = /etc/pgbouncer/~postgres-operator.ini
ignore_startup_parameters = custom
listen_addr = *
listen_port = 8888
server_tls_ca_file = /etc/pgbouncer/~postgres-operator/backend-ca.crt
server_tls_sslmode = verify-full
unix_socket_dir =
verbose = whomp

[databases]
appdb = conn=str

[users]
app = mode=rad
		`, "\t\n")+"\n")

		// The "conffile" setting cannot be changed.
		cluster.Spec.Proxy.PGBouncer.Config.Global["conffile"] = "too-far"
		assert.Assert(t, !strings.Contains(clusterINI(cluster), "too-far"))
	})
}

func TestClusterINIAdminUsers(t *testing.T) {
	t.Parallel()

	newCluster := func(version string) *v1beta1.PostgresCluster {
		cluster := new(v1beta1.PostgresCluster)
		assert.NilError(t, cluster.Default(context.Background(), nil))

		cluster.Name = "foo-baz"
		cluster.SetLabels(map[string]string{v1beta1.LabelVersion: version})

		cluster.Spec.Proxy = new(v1beta1.PostgresProxySpec)
		cluster.Spec.Proxy.PGBouncer = new(v1beta1.PGBouncerPodSpec)
		cluster.Spec.Proxy.PGBouncer.Port = new(int32)
		*cluster.Spec.Proxy.PGBouncer.Port = 8888

		return cluster
	}

	t.Run("Default", func(t *testing.T) {
		cluster := newCluster("3.1.0")
		assert.Assert(t, strings.Contains(clusterINI(cluster),
			"\nadmin_users = _crunchypgbounceradmin\n"))
	})

	t.Run("UserSettingIsKept", func(t *testing.T) {
		cluster := newCluster("3.1.0")
		cluster.Spec.Proxy.PGBouncer.Config.Global = map[string]string{
			"admin_users": "alice, bob",
		}

		assert.Assert(t, strings.Contains(clusterINI(cluster),
			"\nadmin_users = alice, bob,_crunchypgbounceradmin\n"))
	})

	t.Run("NoDuplicateWhenAlreadyListed", func(t *testing.T) {
		cluster := newCluster("3.1.0")
		cluster.Spec.Proxy.PGBouncer.Config.Global = map[string]string{
			"admin_users": "alice,_crunchypgbounceradmin",
		}

		assert.Assert(t, strings.Contains(clusterINI(cluster),
			"\nadmin_users = alice,_crunchypgbounceradmin\n"))
	})

	t.Run("BelowCRVersion", func(t *testing.T) {
		cluster := newCluster("3.0.0")
		assert.Assert(t, !strings.Contains(clusterINI(cluster), "admin_users"))
	})
}

func TestPodConfigFiles(t *testing.T) {
	t.Parallel()

	newCluster := func(version string) *v1beta1.PostgresCluster {
		cluster := &v1beta1.PostgresCluster{
			Spec: v1beta1.PostgresClusterSpec{
				Proxy: &v1beta1.PostgresProxySpec{
					PGBouncer: &v1beta1.PGBouncerPodSpec{
						Config: v1beta1.PGBouncerConfiguration{},
					},
				},
			},
		}
		cluster.SetLabels(map[string]string{v1beta1.LabelVersion: version})

		return cluster
	}
	configmap := &corev1.ConfigMap{ObjectMeta: metav1.ObjectMeta{Name: "some-cm"}}
	secret := &corev1.Secret{ObjectMeta: metav1.ObjectMeta{Name: "some-shh"}}

	t.Run("Default", func(t *testing.T) {
		cluster := newCluster("3.1.0")
		projections := podConfigFiles(cluster, configmap, secret)
		assert.Assert(t, cmp.MarshalMatches(projections, `
- configMap:
    items:
    - key: pgbouncer-empty
      path: pgbouncer.ini
    name: some-cm
- configMap:
    items:
    - key: pgbouncer.ini
      path: ~postgres-operator.ini
    name: some-cm
- secret:
    items:
    - key: pgbouncer-users.txt
      path: ~postgres-operator/users.txt
    name: some-shh
- configMap:
    items:
    - key: pgbouncer-paused
      path: pgbouncer-paused
    name: some-cm
    optional: true
		`))
	})

	// The paused file preserves pause state across restarts and is only
	// projected for clusters at or above the version that introduced it.
	t.Run("PausedFileBelowCRVersion", func(t *testing.T) {
		cluster := newCluster("3.0.0")
		projections := podConfigFiles(cluster, configmap, secret)
		assert.Assert(t, cmp.MarshalMatches(projections, `
- configMap:
    items:
    - key: pgbouncer-empty
      path: pgbouncer.ini
    name: some-cm
- configMap:
    items:
    - key: pgbouncer.ini
      path: ~postgres-operator.ini
    name: some-cm
- secret:
    items:
    - key: pgbouncer-users.txt
      path: ~postgres-operator/users.txt
    name: some-shh
		`))
	})

	t.Run("CustomFiles", func(t *testing.T) {
		cluster := newCluster("3.1.0")
		cluster.Spec.Proxy.PGBouncer.Config.Files = []corev1.VolumeProjection{
			{Secret: &corev1.SecretProjection{
				LocalObjectReference: corev1.LocalObjectReference{Name: "my-thing"},
			}},
			{Secret: &corev1.SecretProjection{
				LocalObjectReference: corev1.LocalObjectReference{Name: "also"},
				Items: []corev1.KeyToPath{
					{Key: "specific", Path: "files"},
				},
			}},
		}

		projections := podConfigFiles(cluster, configmap, secret)
		assert.Assert(t, cmp.MarshalMatches(projections, `
- configMap:
    items:
    - key: pgbouncer-empty
      path: pgbouncer.ini
    name: some-cm
- secret:
    name: my-thing
- secret:
    items:
    - key: specific
      path: files
    name: also
- configMap:
    items:
    - key: pgbouncer.ini
      path: ~postgres-operator.ini
    name: some-cm
- secret:
    items:
    - key: pgbouncer-users.txt
      path: ~postgres-operator/users.txt
    name: some-shh
- configMap:
    items:
    - key: pgbouncer-paused
      path: pgbouncer-paused
    name: some-cm
    optional: true
		`))
	})
}

func TestPgbouncerHBAFileContents(t *testing.T) {
	t.Parallel()

	cluster := new(v1beta1.PostgresCluster)

	t.Run("NoAuthentication", func(t *testing.T) {
		cluster.Spec.Authentication = nil
		result := pgbouncerHBAFileContents(cluster)
		assert.Equal(t, result, "host all all all scram-sha-256\n")
	})

	t.Run("EmptyRules", func(t *testing.T) {
		cluster.Spec.Authentication = &v1beta1.PostgresClusterAuthentication{}
		result := pgbouncerHBAFileContents(cluster)
		assert.Equal(t, result, "host all all all scram-sha-256\n")
	})

	t.Run("NonLDAPRuleSkipped", func(t *testing.T) {
		cluster.Spec.Authentication = &v1beta1.PostgresClusterAuthentication{
			Rules: []v1beta1.PostgresAuthenticationRule{
				{PostgresHBARule: v1beta1.PostgresHBARule{
					Connection: "host",
					Method:     "scram-sha-256",
				}},
			},
		}
		result := pgbouncerHBAFileContents(cluster)
		assert.Equal(t, result, "host all all all scram-sha-256\n")
	})

	t.Run("RawHBANonLDAPSkipped", func(t *testing.T) {
		cluster.Spec.Authentication = &v1beta1.PostgresClusterAuthentication{
			Rules: []v1beta1.PostgresAuthenticationRule{
				{HBA: "host all all all md5"},
			},
		}
		result := pgbouncerHBAFileContents(cluster)
		assert.Equal(t, result, "host all all all scram-sha-256\n")
	})

	t.Run("RawHBALDAPIncluded", func(t *testing.T) {
		cluster.Spec.Authentication = &v1beta1.PostgresClusterAuthentication{
			Rules: []v1beta1.PostgresAuthenticationRule{
				{
					HBA:             "host all all all ldap ldapserver=ldap.example.com",
					PostgresHBARule: v1beta1.PostgresHBARule{Method: "ldap"},
				},
			},
		}
		result := pgbouncerHBAFileContents(cluster)
		assert.Equal(t, result,
			"host all all all ldap ldapserver=ldap.example.com\nhost all all all scram-sha-256\n")
	})

	t.Run("StructuredLDAPRule", func(t *testing.T) {
		cluster.Spec.Authentication = &v1beta1.PostgresClusterAuthentication{
			Rules: []v1beta1.PostgresAuthenticationRule{
				{PostgresHBARule: v1beta1.PostgresHBARule{
					Connection: "hostssl",
					Method:     "ldap",
					Databases:  []string{"mydb"},
					Users:      []string{"myuser"},
					Options: map[string]intstr.IntOrString{
						"ldapserver": intstr.FromString("ldap.example.com"),
						"ldapport":   intstr.FromInt32(389),
					},
				}},
			},
		}
		result := pgbouncerHBAFileContents(cluster)
		assert.Assert(t, strings.HasSuffix(result, "\nhost all all all scram-sha-256\n"))
		assert.Assert(t, strings.HasPrefix(result, "hostssl"))
		assert.Assert(t, strings.Contains(result, "mydb"))
		assert.Assert(t, strings.Contains(result, "myuser"))
		assert.Assert(t, strings.Contains(result, "ldap"))
		assert.Assert(t, strings.Contains(result, "ldapport"))
		assert.Assert(t, strings.Contains(result, "389"))
		assert.Assert(t, strings.Contains(result, "ldapserver"))
		assert.Assert(t, strings.Contains(result, "ldap.example.com"))
	})

	t.Run("StructuredLDAPAllConnectionTypes", func(t *testing.T) {
		for _, tc := range []struct {
			connection string
			wantPrefix string
		}{
			{"hostssl", "hostssl"},
			{"hostnossl", "hostnossl"},
			{"local", "local"},
			{"host", "host"},
			{"", "host"}, // default falls through to TCP
		} {
			cluster.Spec.Authentication = &v1beta1.PostgresClusterAuthentication{
				Rules: []v1beta1.PostgresAuthenticationRule{
					{PostgresHBARule: v1beta1.PostgresHBARule{
						Connection: tc.connection,
						Method:     "ldap",
					}},
				},
			}
			result := pgbouncerHBAFileContents(cluster)
			assert.Assert(t, strings.HasPrefix(result, tc.wantPrefix))
		}
	})

	t.Run("MultipleRules", func(t *testing.T) {
		cluster.Spec.Authentication = &v1beta1.PostgresClusterAuthentication{
			Rules: []v1beta1.PostgresAuthenticationRule{
				{
					HBA:             "hostssl mydb myuser 0.0.0.0/0 ldap ldapserver=a.example.com",
					PostgresHBARule: v1beta1.PostgresHBARule{Method: "ldap"},
				},
				{PostgresHBARule: v1beta1.PostgresHBARule{
					Connection: "host",
					Method:     "scram-sha-256",
				}},
				{PostgresHBARule: v1beta1.PostgresHBARule{
					Connection: "host",
					Method:     "ldap",
					Options: map[string]intstr.IntOrString{
						"ldapserver": intstr.FromString("b.example.com"),
					},
				}},
			},
		}
		result := pgbouncerHBAFileContents(cluster)
		lines := strings.Split(strings.TrimSuffix(result, "\n"), "\n")
		assert.Equal(t, len(lines), 3)
		assert.Equal(t, lines[0], "hostssl mydb myuser 0.0.0.0/0 ldap ldapserver=a.example.com")
		assert.Assert(t, strings.Contains(lines[1], "b.example.com"))
		assert.Equal(t, lines[2], "host all all all scram-sha-256")
	})
}

func TestReloadCommand(t *testing.T) {
	shellcheck := require.ShellCheck(t)
	command := reloadCommand("some-name", true)

	// Expect a bash command with an inline script.
	assert.DeepEqual(t, command[:3], []string{"bash", "-ceu", "--"})
	assert.Assert(t, len(command) > 3)

	// Write out that inline script.
	dir := t.TempDir()
	file := filepath.Join(dir, "script.bash")
	assert.NilError(t, os.WriteFile(file, []byte(command[3]), 0o600))

	// Expect shellcheck to be happy.
	cmd := exec.CommandContext(context.Background(), shellcheck, "--enable=all", file)
	output, err := cmd.CombinedOutput()
	assert.NilError(t, err, "%q\n%s", cmd.Args, output)
}
