---
# Wait for the clone cluster to come online.
apiVersion: upstream.pgv2.percona.com/v2
kind: PostgresCluster
metadata:
  name: clone-one
status:
  instances:
    - name: '00'
      replicas: 1
      readyReplicas: 1
      updatedReplicas: 1
