#!/bin/bash

set -o errexit
set -o xtrace

test_dir=$(realpath $(dirname $0))
. ${test_dir}/../functions

create_namespace $namespace
deploy_operator

cluster="some-name"
spinup_pgcluster "${cluster}" "${src_dir}/deploy/cr.yaml"

compare_kubectl "deployment/${cluster}"
compare_kubectl "deployment/${cluster}-backrest-shared-repo"
compare_kubectl "job/backrest-backup-${cluster}"

kubectl_bin delete perconapgcluster ${cluster}
sleep 30

cluster="some-name-required"
spinup_pgcluster "${cluster}" "${src_dir}/deploy/cr.yaml" '' '' "required"

compare_kubectl "deployment/${cluster}"
compare_kubectl "deployment/${cluster}-backrest-shared-repo"
compare_kubectl "job/backrest-backup-${cluster}"

kubectl_bin delete perconapgcluster ${cluster}
sleep 30

cluster="some-name-disabled"
spinup_pgcluster "${cluster}" "${src_dir}/deploy/cr.yaml" '' '' "disabled"

compare_kubectl "deployment/${cluster}"
compare_kubectl "deployment/${cluster}-backrest-shared-repo"
compare_kubectl "job/backrest-backup-${cluster}"

destroy ${namespace}
