apiVersion: pgv2.percona.com/v2
kind: PerconaPGBackup
metadata:
  name: backup1
spec:
  pgCluster: cluster1
  repoName: repo1
#  containerOptions:
#    env:
#    - name: MY_ENV
#      value: "1000"
#    envFrom:
#    - secretRef:
#        name: backup-env-secret
#  options:
#  - --type=full
