apiVersion: v1
kind: Secret
metadata:
  name: cluster1-users-secrets
type: Opaque
stringData:
  pgbouncer: pgbouncer_password
  postgres: postgres_password
  primaryuser: primaryuser_password
  pguser: pguser_password
---
apiVersion: v1
data:
  password: YWRtaW4=
  username: YWRtaW4=
kind: Secret
metadata:
  name: some-name-pmm-secret
type: Opaque
