apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../crd
- ../rbac/namespace
- ../manager/namespace
images:
- name: postgres-operator
  newName: docker.io/perconalab/percona-postgresql-operator
  newTag: CNGTM-214-7e0766b2763adf0dc3e82e738a10a58e8f018cb8
