#!/bin/bash

set -o errexit
set -o xtrace

exec 5>&2
export BASH_XTRACEFD="5"

ROOT_REPO=${ROOT_REPO:-${PWD}}
source "${ROOT_REPO}/e2e-tests/vars.sh"

BUILD_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
GIT_COMMIT=$(git rev-parse HEAD)
IMAGE=${IMAGE/#percona\//perconalab/}

if [[ ${DOCKER_NOCACHE:-0} == 1 ]]; then
	no_cache="--no-cache"
fi
if [[ ${DOCKER_SQUASH:-1} == 1 ]]; then
	squash="--squash"
fi


if [[ ${DOCKER_PUSH:-1} == 1 ]]; then
	imgresult="--push=true"
else
	imgresult="--load"
fi

BUILD_COMPONENT=${COMPONENT:-"postgres-operator"}

build_operator() {
	if [ "${RELEASE:-1}" = 0 ]; then
		GO_LDFLAGS="-race"
	fi

	export DOCKER_DEFAULT_PLATFORM=${DOCKER_DEFAULT_PLATFORM:-"linux/amd64,linux/arm64"}
	export GO_LDFLAGS="-w -s -trimpath ${GO_LDFLAGS}"
	pushd "${ROOT_REPO}" || exit
	docker buildx build \
		--platform $DOCKER_DEFAULT_PLATFORM \
		--build-arg GIT_COMMIT="${GIT_COMMIT}" \
		--build-arg GIT_BRANCH="${GIT_BRANCH}" \
		--build-arg BUILD_TIME="${BUILD_TIME}" \
		--build-arg GO_LDFLAGS="${GO_LDFLAGS}" \
		$imgresult \
		$squash \
		$no_cache \
		-t "${IMAGE}" -f build/${BUILD_COMPONENT}/Dockerfile .
	popd || exit
}

if [[ $BUILD == "0" ]]; then
	exit 0
fi

# wait for docker
until docker info >/dev/null; do sleep 1; done

build_operator
