#!/bin/bash

set -o xtrace
set -o errexit

dir=$(realpath "$(dirname "$0")")

fail() {
	local test=$1
	echo "test $test failed"
	exit 1
}

$dir/init-deploy/run           || fail "init-deploy"
$dir/scaling/run               || fail "scaling"
$dir/recreate/run              || fail "recreate"
$dir/affinity/run              || fail "affinity"
$dir/monitoring/run            || fail "monitoring"
$dir/self-healing/run          || fail "self-healing"
$dir/operator-self-healing/run || fail "operator-self-healing"
$dir/clone-cluster/run         || fail "clone-cluster"
$dir/users/run                 || fail "users"
$dir/ns-mode/run               || fail "ns-mode"
$dir/demand-backup/run         || fail "demand-backup"
$dir/scheduled-backup/run      || fail "scheduled-backup"
$dir/upgrade/run               || fail "upgrade"
$dir/smart-update/run          || fail "smart-update"
$dir/version-service/run       || fail "version-service"
