package naming

const (
	// AnnotationPGBackrestBackup is the annotation that is added to a PerconaPGCluster to initiate a manual
	// backup.  The value of the annotation will be a unique identifier for a backup Job (e.g. a
	// timestamp), which will be stored in the PostgresCluster status to properly track completion
	// of the Job.  Also used to annotate the backup Job itself as needed to identify the backup
	// ID associated with a specific manual backup Job.
	AnnotationPGBackrestBackup = PrefixPerconaPGV2 + "pgbackrest-backup"

	// AnnotationPGBackrestBackupJobName is the annotation that is added to a PerconaPGClusterBackup.
	// The value of the annotation will be a name of an existing backup job
	AnnotationPGBackrestBackupJobName = AnnotationPGBackrestBackup + "-job-name"

	// AnnotationPGBackrestBackupJobType is the annotation that is added to a PerconaPGClusterBackup.
	// The value of the annotation will be a type of a backup (e.g. "manual" or "replica-create).
	AnnotationPGBackrestBackupJobType = AnnotationPGBackrestBackup + "-job-type"

	// AnnotationPGBackRestRestore is the annotation that is added to a PerconaPGCluster to initiate an in-place
	// restore.  The value of the annotation will be a unique identfier for a restore Job (e.g. a
	// timestamp), which will be stored in the PostgresCluster status to properly track completion
	// of the Job.
	AnnotationPGBackRestRestore = PrefixPerconaPGV2 + "pgbackrest-restore"

	// AnnotationPMMSecretHash is the annotation that is added to instance annotations to
	// rollout restart PG pods in case PMM credentials are rotated.
	AnnotationPMMSecretHash = PrefixPerconaPGV2 + "pmm-secret-hash"

	// AnnotationMonitorUserSecretHash is the annotation that is added to instance annotations to
	// rollout restart PG pods in case monitor user password is changed.
	AnnotationMonitorUserSecretHash = PrefixPerconaPGV2 + "monitor-user-secret-hash"

	// AnnotationEnvVarsSecretHash is the annotation that is added to
	// rollout restart pods in case envFrom secret is changed.
	AnnotationEnvVarsSecretHash = PrefixPerconaPGV2 + "env-secret-config-hash"

	// AnnotationLogCollectorConfigHash is the annotation that is added to instance
	// annotations to rollout restart PG pods when the log collector (fluent-bit /
	// logrotate) configuration changes. The config is delivered through ConfigMaps
	// mounted by a stable name, so its content changes do not alter the pod template
	// on their own; this hash makes them do so.
	AnnotationLogCollectorConfigHash = PrefixPerconaPGV2 + "logcollector-config-hash"

	// AnnotationBackupInProgress is the annotation that is added to PerconaPGCluster to
	// indicate that backup is in progress.
	AnnotationBackupInProgress = PrefixPerconaPGV2 + "backup-in-progress"

	// AnnotationClusterBootstrapRestore is the annotation that is added to PerconaPGRestore to
	// indicate that it is a cluster bootstrap restore.
	AnnotationClusterBootstrapRestore = PrefixPerconaPGV2 + "cluster-bootstrap-restore"

	AnnotationPatroniVersion = PrefixPerconaPGV2 + "patroni-version"

	// Special annotation to disable `patroni-version-check` by overriding the patroni version with a custom value.
	AnnotationCustomPatroniVersion = PrefixPerconaPGV2 + "custom-patroni-version"

	// AnnotationReplicationMainSite is the annotation that is added to a standby PerconaPGCluster to
	// indicate the name of the main site.
	// This annotation is set on standby clusters based on pgbackrest only. This is needed to calculate the replication lag.
	AnnotationReplicationMainSite = PrefixPerconaPGV2 + "replication-main-site"

	// AnnotationInstanceSuspended must be set on the instance StatefulSet to mark
	// the instance as suspended.
	AnnotationInstanceSuspended = PrefixPerconaPGV2 + "instance-suspended"

	// AnnotationSnapshotRestore is the annotation added to the data PVCs of a cluster
	// to indicate the name of the PerconaPGRestore that is restoring the PVC from a snapshot.
	AnnotationSnapshotRestore = PrefixPerconaPGV2 + "snapshot-restore"

	// AnnotationPVCsPreparedAt is the annotation added to the PerconaPGRestore which
	// prepares the PVCs for a snapshot restore.
	AnnotationPVCsPreparedAt = PrefixPerconaPGV2 + "pvcs-prepared-at"

	// AnnotationExternalDNSHostname and AnnotationExternalDNSTTL are the external-dns
	// annotations the operator writes on a Service from its expose.externalDNS section.
	AnnotationExternalDNSHostname = "external-dns.alpha.kubernetes.io/hostname"
	AnnotationExternalDNSTTL      = "external-dns.alpha.kubernetes.io/ttl"

	// AnnotationExternalDNSManaged marks a Service whose external-dns annotations are
	// generated by the operator, and is how the operator tracks ownership of them.
	// Services without it are never touched, so the manual per-Service annotation
	// workflow keeps working.
	AnnotationExternalDNSManaged = PrefixPercona + "external-dns-managed"
)

// ManagedExternalDNSHostnames returns the external-dns hostnames the operator
// wrote itself, gathered from the given annotation maps. It is used to add
// those hostnames to certificate SANs, so a client can reach the cluster
// through its external name with sslmode=verify-full.
//
// Only hostnames carrying AnnotationExternalDNSManaged are returned. A hostname
// a user wrote by hand into expose.annotations has no marker and is skipped, so
// existing clusters do not silently get their certificates reissued.
func ManagedExternalDNSHostnames(annotations ...map[string]string) []string {
	hostnames := make([]string, 0, len(annotations))

	for _, a := range annotations {
		if a[AnnotationExternalDNSManaged] != "true" {
			continue
		}
		if hostname := a[AnnotationExternalDNSHostname]; hostname != "" {
			hostnames = append(hostnames, hostname)
		}
	}

	return hostnames
}
