apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgres-operator

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: pgo
    # The version below should match the version on the PostgresCluster CRD
    app.kubernetes.io/version: 5.5.1
    postgres-operator.crunchydata.com/control-plane: postgres-operator

resources:
- ../crd
- ../rbac/namespace
- ../manager

images:
- name: postgres-operator
  newName: registry.developers.crunchydata.com/crunchydata/postgres-operator
  newTag: latest

patches:
- manager-target.yaml
