apiVersion: pg.percona.com/v1
kind: Pgtask
metadata:
  labels:
    pg-cluster: cluster1
    pgouser: admin
  name: backrest-demand-backup-cluster1
spec:
  name: backrest-demand-backup-cluster1
  namespace: pgo
  parameters:
    backrest-command: backup
    backrest-opts: '--type=full'
    backrest-s3-verify-tls: 'false'
    containername: database
    image-prefix: perconalab/percona-postgresql-operator
    job-name: backrest-demand-backup-cluster1
    pg-cluster: cluster1
    pgha-backup-type: bootstrap
    podname: cluster1-backrest-shared-repo-6c894bb76d-4fdlq
  status: ''
  storagespec:
    accessmode: ''
    matchLabels: ''
    name: ''
    size: ''
    storageclass: ''
    storagetype: ''
    supplementalgroups: ''
  tasktype: backrest
