kind: ConfigMap
apiVersion: v1
metadata:
  name: some-name-custom-config
data:
  postgres-ha.yaml: |
    ---
    bootstrap:
      dcs:
        postgresql:
          parameters:
            track_commit_timestamp: on