kind: ConfigMap
apiVersion: v1
metadata:
  name: some-name-custom-config
data:
  postgres-ha.yaml: |
    ---
    bootstrap:
      dcs:
        postgresql:
          parameters:
            track_commit_timestamp: on
            max_connections: 30
            shared_buffers: 2GB
            password_encryption: scram-sha-256