---
# Update the postgres version and restart the cluster.
apiVersion: upstream.pgv2.percona.com/v2
kind: PostgresCluster
metadata:
  name: major-upgrade-empty-image
spec:
  shutdown: false
  postgresVersion: ${KUTTL_PG_UPGRADE_FROM_VERSION}
---
apiVersion: upstream.pgv2.percona.com/v2
kind: PGUpgrade
metadata:
  name: empty-image-upgrade
spec:
  # update postgres version
  fromPostgresVersion: ${KUTTL_PG_UPGRADE_FROM_VERSION}
