---
# Once the pgupgrade is finished, update the version and set shutdown to false
# in the postgres cluster
apiVersion: upstream.pgv2.percona.com/v2
kind: PostgresCluster
metadata:
  name: major-upgrade-empty-image
spec:
  postgresVersion: ${KUTTL_PG_UPGRADE_TO_VERSION}
  shutdown: false
