#!/bin/bash

set -o errexit
set -o xtrace

test_dir=$(realpath $(dirname $0))
. ${test_dir}/../functions

function prepare_n_restore {
	local cluster=${1}
	local storage=${2}
	local backup_type=${3}
	local restore_target=''

	create_backup ${cluster} "initialbackup" ${backup_type}

	run_psql \
		'\c myapp \\\ INSERT INTO myApp (id) VALUES (100501)' \
		"postgres:$(get_psql_user_pass postgres ${cluster})@${cluster}.${namespace}"

	compare_psql_cmd \
		"select-1" \
		'\c myapp \\\ SELECT * from myApp;' \
		"postgres:$(get_psql_user_pass postgres ${cluster})@${cluster}.${namespace}"

	run_psql \
		'\c myapp \\\ INSERT INTO myApp (id) VALUES (100502)' \
		"postgres:$(get_psql_user_pass postgres ${cluster})@${cluster}.${namespace}"

	restore_target="$(run_psql \
		'\c myapp \\\ SELECT xmin FROM myApp WHERE id='100501';' \
		"postgres:$(get_psql_user_pass postgres ${cluster})@${cluster}.${namespace}" | awk '{$1=$1;print}')"

	run_psql \
		'DROP DATABASE myapp' \
		"postgres:$(get_psql_user_pass postgres ${cluster})@${cluster}.${namespace}"

	run_restore ${cluster} ${backup_type} ${storage} "${restore_target}" 'xid'

	compare_psql_cmd \
		"select-1" \
		'\c myapp \\\ SELECT * from myApp;' \
		"postgres:$(get_psql_user_pass postgres ${cluster})@${cluster}.${namespace}"
}

function apply_configs {
	local cluster=${1}
	local backup_storage_type=${2:-""}

	set +x
	yq w $test_dir/conf/backrest-repo-secret.yml 'metadata.name' "${cluster}-backrest-repo-config" \
		| yq w - 'data[aws-s3-key]' "$(yq r -d"0" ${conf_dir}/cloud-secret.yml 'data.AWS_ACCESS_KEY_ID')" \
		| yq w - 'data[aws-s3-key-secret]' "$(yq r -d"0" ${conf_dir}/cloud-secret.yml 'data.AWS_SECRET_ACCESS_KEY')" \
		| yq w - 'data[gcs-key]' "$(yq r -d0 ${conf_dir}/cloud-secret-minio-gw.yml 'stringData."credentials.json"' | base64)" \
			>/tmp/repo.secret.yaml
	if [[ ${backup_storage_type} == "minio" ]]; then
		yq w -i /tmp/repo.secret.yaml 'data[aws-s3-key]' "$(echo -n some-access-key | base64)"
		yq w -i /tmp/repo.secret.yaml 'data[aws-s3-key-secret]' "$(echo -n some-secret-key | base64)"
		# yq w -i /tmp/repo.secret.yaml 'data[aws-s3-ca]' "$(kubectl_bin get secret/minio-gw-tls -o jsonpath='{.data.ca\.crt}')"
	fi
	kubectl_bin apply -f /tmp/repo.secret.yaml
	rm -rf /tmp/repo.secret.yaml
	set -x
	yq r $test_dir/conf/custom-config.yml \
		| yq w - 'metadata.name' "${cluster}-custom-config" \
		| kubectl_bin apply -f -
}

function main {
	create_namespace $namespace
	deploy_cert_manager
	deploy_operator
	deploy_minio

	desc 'create first PG cluster'
	cluster="some-name-${RANDOM}"

	desc 'Testing backup/restore from minio (self-signed crt)'
	apply_configs ${cluster} 'minio'
	spinup_pgcluster "${cluster}" "${src_dir}/deploy/cr.yaml" "minio" "${cluster}-custom-config"

	# custom parameters check
	compare_psql_cmd \
		"show-1" \
		'show max_connections;' \
		"postgres:$(get_psql_user_pass postgres ${cluster})@${cluster}.${namespace}"
	compare_psql_cmd \
		"show-2" \
		'show password_encryption;' \
		"postgres:$(get_psql_user_pass postgres ${cluster})@${cluster}.${namespace}"

	prepare_n_restore ${cluster} "s3" "incr"

	kubectl_bin delete perconapgcluster/${cluster}
	sleep 60
	destroy_minio
	apply_configs ${cluster}

	sleep 30

	desc 'Testing backup/restore from gcs'
	apply_configs ${cluster}
	spinup_pgcluster "${cluster}" "${src_dir}/deploy/cr.yaml" "gcs" "${cluster}-custom-config"
	prepare_n_restore ${cluster} "gcs" "incr"

	kubectl_bin delete perconapgcluster/${cluster}
	sleep 30

	gsutil -m rm -r gs://${BUCKET}/backrestrepo/${cluster}-backrest-shared-repo


	desc 'Testing backup/restore from local'
	apply_configs ${cluster}
	spinup_pgcluster "${cluster}" "${src_dir}/deploy/cr.yaml" "local" "${cluster}-custom-config"
	prepare_n_restore ${cluster} "posix" "full"

	kubectl_bin delete perconapgcluster/${cluster}
	sleep 60

	desc 'Testing backup/restore from local with storage hybrid storage, posix'
	apply_configs ${cluster}
	spinup_pgcluster "${cluster}" "${src_dir}/deploy/cr.yaml" "local,s3" "${cluster}-custom-config"
	prepare_n_restore ${cluster} "posix" "diff"

	kubectl_bin delete perconapgcluster/${cluster}
	sleep 60

	desc 'Testing backup/restore from local with storage hybrid storage, gcs'
	apply_configs ${cluster}

	spinup_pgcluster "${cluster}" "${src_dir}/deploy/cr.yaml" "local,gcs" "${cluster}-custom-config"
	prepare_n_restore ${cluster} "gcs" "diff"

	destroy ${namespace}
}

main
