#!/bin/bash

set -o errexit
set -o xtrace

test_dir=$(realpath $(dirname $0))
. ${test_dir}/../functions

create_namespace $namespace
deploy_cert_manager
deploy_operator

desc 'create first PSMDB cluster'
cluster="some-name-${RANDOM}"

deploy_miniogw

kubectl_bin get secret/minio-gw-tls -o jsonpath='{.data.tls\.crt}'

yq w $conf_dir/cloud-secret.yml 'metadata.name' "${cluster}-backrest-repo-config" \
	| yq w - 'data[aws-s3-ca.crt]' $(kubectl_bin get secret/minio-gw-tls -o jsonpath='{.data.tls\.crt}') \
	| kubectl_bin apply -f -
yq r -d0 $conf_dir/some-name-secrets.yml \
	| yq w - 'metadata.name' "${cluster}-pgbouncer-secret" \
	| yq w - 'metadata.labels.pg-cluster' "${cluster}" \
	| kubectl_bin apply -f -
yq r -d1 $conf_dir/some-name-secrets.yml \
	| yq w - 'metadata.name' "${cluster}-postgres-secret" \
	| yq w - 'metadata.labels.pg-cluster' "${cluster}" \
	| kubectl_bin apply -f -
yq r -d2 $conf_dir/some-name-secrets.yml \
	| yq w - 'metadata.name' "${cluster}-primaryuser-secret" \
	| yq w - 'metadata.labels.pg-cluster' "${cluster}" \
	| kubectl_bin apply -f -
yq r -d3 $conf_dir/some-name-secrets.yml \
	| yq w - 'metadata.name' "${cluster}-${cluster}-secret" \
	| yq w - 'metadata.labels.pg-cluster' "${cluster}" \
	| kubectl_bin apply -f -

yq r $test_dir/conf/custom-config.yml \
	| yq w - 'metadata.name' "${cluster}-custom-config" \
	| kubectl_bin apply -f -

kubectl_bin apply \
	-f $conf_dir/client.yml

spinup_pgcluster "${cluster}" "${src_dir}/deploy/cr.yaml" "true" "${cluster}-custom-config"

create_backup ${cluster} "initialbackup" "incr"

run_psql \
	'\c myapp \\\ INSERT INTO myApp (id) VALUES (100501)' \
	"postgres:postgres_pass@${cluster}.${namespace}"

run_psql \
	'\c myapp \\\ INSERT INTO myApp (id) VALUES (100502)' \
	"postgres:postgres_pass@${cluster}.${namespace}"
sleep 1
RESTORE_TIME="$(run_psql \
				'\c myapp \\\ SELECT pg_xact_commit_timestamp(xmin) FROM myApp WHERE id='100501';' \
				"postgres:postgres_pass@${cluster}.${namespace}" | awk '{$1=$1;print}')"

run_psql \
	'DROP DATABASE myapp' \
	"postgres:postgres_pass@${cluster}.${namespace}"

run_restore ${cluster} "full" "s3" "${RESTORE_TIME}"

compare_psql_cmd \
	"select-1" \
	'\c myapp \\\ SELECT * from myApp;' \
	"postgres:postgres_pass@${cluster}.${namespace}"
