apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: ldap
status:
  instances:
    - name: instance1
      readyReplicas: 1
      replicas: 1
      updatedReplicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: ldap-primary
